Todo_List/Todo_List/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Todo_List_App.urls'))
]

Todo_List/Todo_List_App/models.py
from django.contrib.auth.models import AbstractUser , User
from django.db import models
from django.utils import timezone
from django.conf import settings
import os

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=100)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.username
    
class Task(models.Model):
    taskTitle = models.CharField(max_length=200)
    description = models.TextField(null = True, blank = True)
    category = models.ForeignKey('Category', related_name='tasks', on_delete=models.CASCADE, null=True)
    dueDate = models.DateTimeField(db_column = 'duedate')
    completedDate = models.DateTimeField(null=True, blank=True)
    createdDate = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    important = models.BooleanField(default=False)
    status = models.CharField(max_length=100, default='Pending')
        
    def __str__(self):
        return self.taskTitle

class Category(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class CompletedTask(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.task.taskTitle

def profile_picture_path(instance, filename):
    return os.path.join('profile_pictures', str(instance.user.id), filename)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to=profile_picture_path, default='profile_pictures/default.jpg')
    completed_tasks_count = models.PositiveIntegerField(default=0)
    first_name = models.CharField(max_length=30, blank=True)  
    last_name = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=100, blank=True) 


    def update_completed_tasks_count(self):
        self.completed_tasks_count = self.user.task_set.filter(completed=True).count()
        self.save()

    def __str__(self):
        return self.user.username

class Solve(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()

Todo_List/Todo_List_App/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, SetPasswordForm, UserChangeForm
from django.contrib.auth import get_user_model
from Todo_List_App.models import Profile, CustomUser
from django.contrib.auth.models import User

User = get_user_model()

class CustomUserAdminForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = '__all__'
class SignInForm(AuthenticationForm):
    pass

class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    phone = forms.CharField(max_length=15, required=False, help_text='Optional.')
    address = forms.CharField(max_length=100, required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'phone', 'address', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('This username is already in use. Please choose a different one.')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email address is already associated with an account.')
        return email

class ProfileForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'autocomplete': 'off'}))
    first_name = forms.CharField(max_length=30, required=False, label="First Name")
    last_name = forms.CharField(max_length=30, required=False, label="Last Name")
    phone = forms.CharField(max_length=15, required=False)
    address = forms.CharField(max_length=100, required=False)

    class Meta:
        model = Profile
        fields = ['email','phone','address', 'profile_picture']

    def clean_email(self):
        email = self.cleaned_data['email']
        user = self.instance.user

        if User.objects.exclude(pk=user.pk).filter(email=email).exists():
            raise forms.ValidationError('This email address is already associated with an account.')

        return email

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name and last_name:
            full_name = f"{first_name} {last_name}"
            self.instance.full_name = full_name

        return cleaned_data

class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label="New Password", widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="Confirm New Password", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 != new_password2:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data

class SolveForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()

Todo_List/templates/Sign_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: Arial, sans-serif;
        }
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 80vh;
        }
        .form {
            background-color: #fff;
            color: #000;
            padding: 30px;
            border-radius: 10px;
            max-width: 600px;
            text-align: center;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-left:-10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            outline: none;
        }

        .input-group {
            position: relative;
        }

        .input-group i {
            position: absolute;
            right: -5px;
            top: 35%;
            down: 50%;
            transform: translateY(-50%);
            cursor: pointer;
        }
        
        input[type="submit"] {
            background-color: #000;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
        .signup-link {
            color: black;
            text-decoration: none;
        }
        .signup-link:hover {
            text-decoration: underline;
        }
        .alert-box {
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            font-weight: bold;
        }
        .alert-box.alert-danger {
            background-color: #ff0000;
            color: #ffffff;
            border: 2px solid #ff0000;
        }
        .alert-box.alert-success {
            background-color: #00ff00;
            color: #ffffff;
            border: 2px solid #00ff00;
        }
    </style>
</head>
<body>
    <div class="container">
        <form class="form" method="post" action="{% url 'signin' %}">
            {% csrf_token %}
            <h2>Login</h2>
            <div class="input-group">
                <input type="text" name="username" placeholder="Username"style="margin-bottom:17px;" required>
            </div>
            <div class="input-group">
                <input type="password" name="password" placeholder="Password"style="margin-bottom:20px;" required>
                <i class="fa fa-eye" id="eye"></i>
            </div>
            <div class="remember-forgot">
                <input type="checkbox" name="remember_me" id="remember_me"style="margin-left:-5px;">
                <label for="remember_me"style="margin-right:100px;">Remember me</label>
                <a href="{% url 'forgot_password' %}" class="forgot-link"style="color:blue;">Forgot password?</a><br>
            </div><br>
            <input type="submit" value="Login"style="margin-bottom:15px;">
            <br>Don't have an account?<p class = "signup-link"><a href="{% url 'signup' %}"style="color:blue;"><b>Sign up</b></a></p>
            {% if messages %}
                <div class="text-center mt-3">
                    {% for message in messages %}
                        <div class="alert-box {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% else %}alert-success{% endif %}">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </form>
    </div>
    <script>
        const eye = document.getElementById('eye');
        const password = document.querySelector('input[name="password"]');
        eye.addEventListener('click', () => {
            if (password.type === 'password') {
                password.type = 'text';
                eye.classList.add('fa-eye-slash');
            } else {
                password.type = 'password';
                eye.classList.remove('fa-eye-slash');
            }
        });
    </script>
</body>
</html>

Todo_List/templates/Sign_up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: Arial, sans-serif;
        }
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 90vh;
        }
        .form {
            background-color: #fff;
            color: #000;
            padding: 30px;
            border-radius: 10px;
            max-width: 400px;
            text-align: center;
        }
        input[type="text"],
        input[type="email"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-left:-10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            outline: none;
        }

        .input-group {
            position: relative;
        }

        .input-group i {
            position: absolute;
            right: -5px;
            top: 35%;
            down: 50%;
            transform: translateY(-50%);
            cursor: pointer;
        }
        
        input[type="submit"] {
            background-color: #000;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
        .signup-link {
            color: black;
            text-decoration: none;
        }
        .signup-link:hover {
            text-decoration: underline;
        }
        .alert-box {
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            font-weight: bold;
        }
        .alert-box.alert-danger {
            background-color: #ff0000;
            color: #ffffff;
            border: 2px solid #ff0000;
        }
        .alert-box.alert-success {
            background-color: #00ff00;
            color: #ffffff;
            border: 2px solid #00ff00;
        }
    </style>
</head>
<body>
    <div class="container">
        <form class="form" method="post">
            <h2>Sign up</h2>
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required>
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <div class="alert-box alert-danger">
                        {{ error }}<br>
                    </div>
                {% endfor %}
            {% endif %}
            <input type="email" name="email" placeholder="Email" required>
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                    <div class="alert-box alert-danger">
                        {{ error }}<br>
                    </div>
                {% endfor %}
            {% endif %}
            <input type="text" name="first_name" placeholder="First Name" required>
            <input type="text" name="last_name" placeholder="Last Name" required>
            <input type="text" name="phone" placeholder="Phone" required>
            <input type="text" name="address" placeholder="Address" required>
            <div class="input-group">
                <input type="password" name="password1" placeholder="Password" required>
                <i class="fa fa-eye toggle-password" id="eye1"></i>
            </div>
            <div class="input-group">
                <input type="password" name="password2" placeholder="Confirm Password" required>
                <i class="fa fa-eye toggle-password" id="eye2"></i>
            </div>
            {% if form.password1.errors %}
                {% for error in form.password1.errors %}
                    <div class="alert-box alert-danger">
                        {{ error }}<br>
                    </div>
                {% endfor %}
            {% endif %}
            {% if form.password2.errors %}
                {% for error in form.password2.errors %}
                    <div class="alert-box alert-danger">
                        {{ error }}<br>
                    </div>
                {% endfor %}
            {% endif %}
            <input type="submit" value="Sign Up">
            <p>Already have an account? <a href="{% url 'signin' %}"style="color:blue;"><b>Sign in</b></a></p>
            {% if messages %}
                <div class="text-center mt-3">
                    {% for message in messages %}
                        <div class="alert-box {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}">
                            {{ message }}<br>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </form>
    </div>
    <script>
        const eyes = document.querySelectorAll('.toggle-password');
        const passwords = [document.querySelector('input[name="password1"]'), document.querySelector('input[name="password2"]')];
    
        eyes.forEach((eye, index) => {
            eye.addEventListener('click', () => {
                if (passwords[index].type === 'password') {
                    passwords[index].type = 'text';
                    eye.classList.add('fa-eye-slash');
                } else {
                    passwords[index].type = 'password';
                    eye.classList.remove('fa-eye-slash');
                }
            });
        });
    </script>
</body>
</html>

Todo_List/templates/add_category.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ADD CATEGORY - TODO LIST</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'add.png' %}">
</head>
<body>
    {% include 'base.html' %}
<div class="container my-3">
    <h3 class="text-center">Add Category</h3>
    <div class="d-flex justify-content-center">
        <div style="width: 800px;">
            <form method="POST" action="/add-category/">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="category" class="form-label">Category Name :</label>
                    <input type="text" class="form-control" id="category" name="name" placeholder="EX : HOME" required>
                </div>
                <button type="submit" class="btn btn-primary btn-add">Add</button>
            </form>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                    <br><br>
                    <div class="alert alert-danger alert-dismissible mt-3 text-center" role="alert" style="width: 800px;">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endif %}
                    {% if message.tags == 'success' %}
                    <br><br>
                    <div class="alert alert-success alert-dismissible mt-3 text-center" role="alert" text-center style="width:800px;">
                        Category created successfully! Lets <a href="{% url 'Todo_List_App' %}" class="alert-link"style="color:green;"> Create a Task</a>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

Todo_List/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="icon" type="image/png" href="{% static 'profile.png' %}">
    <style>
        .fa-eye-slash {
            color: #999;
            cursor: pointer;
        }
        .fa-eye-slash:hover {
            color: #666;
        }
        .input-group i {
            position: absolute;
            right: 10px;
            top: 50%;
            transform: translateY(-50%);
        }
    </style>
</head>
<body>
    {% include 'base.html' %}
    <div class="profile-section">
        <div class="profile-picture">
            <img src="{{ user.profile.profile_picture.url }}" class="rounded-circle" width="250" height="250" alt="Profile Picture">
        </div>
        <div class="profile-details">
            <h3 class="username">{{ user.username }}</h3>
            <p class="completed-tasks">Total Completed Tasks : {{ user.profile.completed_tasks_count }}</p>
        </div>
    </div>
    
    <div class="container my-3">
        <h2 class="text-center">Profile</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_profile_picture" class="form-label" style="margin-top: 50px">Profile Picture:</label>
                <input type="file" class="form-control" name="profile_picture" id="id_profile_picture">
                {% if form.profile_picture.errors %}
                    <div class="errors">
                        {% for error in form.profile_picture.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_first_name" class="form-label">First Name:</label>
                <input type="text" class="form-control" name="first_name" id="id_first_name" value="{{ user.first_name }}">
            </div>
            <div class="mb-3">
                <label for="id_last_name" class="form-label">Last Name:</label>
                <input type="text" class="form-control" name="last_name" id="id_last_name" value="{{ user.last_name }}">
            </div>
            <div class="mb-3">
                <label for="id_phone" class="form-label">Phone Number:</label>
                <input type="text" class="form-control" name="phone" id="id_phone" value="{{ user.phone }}">
            </div>
            <div class="mb-3">
                <label for="id_address" class="form-label">Address:</label>
                <input type="text" class="form-control" name="address" id="id_address" value="{{ user.address }}">
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Email:</label>
                <input type="email" class="form-control" name="email" id="id_email" value="{{ user.email }}">
                {% if form.email.errors %}
                    <div class="errors">
                        {% for error in form.email.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="change_password" class="form-label">Change Password:</label>
                <select class="form-select" name="change_password" id="change_password">
                    <option value="no_change">No Change</option>
                    <option value="change">Change Password</option>
                </select>
            </div>
            <div id="password_fields" style="display: none;">
                <div class="mb-3 input-group">
                    <label for="id_old_password" class="form-label">Old Password:</label>
                    <input type="password" class="form-control" name="old_password" id="id_old_password">
                    <i class="fa fa-eye toggle-password" id="eye_old_password"></i>
                    {% if password_form.old_password.errors %}
                        <div class="errors">
                            {% for error in password_form.old_password.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3 input-group">
                    <label for="id_new_password1" class="form-label">New Password:</label>
                    <input type="password" class="form-control" name="new_password1" id="id_new_password1">
                    <i class="fa fa-eye toggle-password" id="eye_new_password1"></i>
                    {% if password_form.new_password1.errors %}
                        <div class="errors">
                            {% for error in password_form.new_password1.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3 input-group">
                    <label for="id_new_password2" class="form-label">Confirm New Password:</label>
                    <input type="password" class="form-control" name="new_password2" id="id_new_password2">
                    <i class="fa fa-eye toggle-password" id="eye_new_password2"></i>
                    {% if password_form.new_password2.errors %}
                        <div class="errors">
                            {% for error in password_form.new_password2.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            
            <button type="submit" class="btn btn-primary btn-add" style = "background-color:#0DBEF3;">Save</button>
        </form>
        <br>
        <form method="POST" action="{% url 'delete_account' user.id %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="confirm" class="form-label">Option :</label>
                <select class="form-select" name="confirm" id="confirm">
                    <option value="no_change">No Change</option>
                    <option value="delete_account" required>DELETE  ACCOUNT</option>
                </select>
            </div>
            <div id="delete_account" style="display: none;">
                <div class="mb-3">
                    <label for="confirm" class="form-label" style="color:#EC7063;">WARNING : This action can't be reversed, type "CONFIRM" to delete account.</label>
                    <input type="text" class="form-control" name="confirm" id="confirm">
                </div>
            </div>
            <button type="submit" class="btn btn-danger">Delete Account</button>
        </form>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#change_password").change(function() {
                var passwordFields = $("#password_fields");
                console.log($(this).val())
                if ($(this).val() === "change") {
                    passwordFields.show();
                    passwordFields.find("input").prop("required", true);
                } else {
                    passwordFields.hide();
                    passwordFields.find("input").prop("required", false);
                }
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            $("#confirm").change(function() {
                var deleteAccount = $("#delete_account");
                console.log($(this).val())
                if ($(this).val() === "delete_account") {
                    deleteAccount.show();
                    deleteAccount.find("input").prop("required", true);
                } else {
                    deleteAccount.hide();
                    deleteAccount.find("input").prop("required", false);
                }
            });
        });
    </script>
    <script>
        const eyeOldPassword = document.getElementById('eye_old_password');
        const oldPassword = document.querySelector('input[name="old_password"]');
        
        const eyeNewPassword1 = document.getElementById('eye_new_password1');
        const newPassword1 = document.querySelector('input[name="new_password1"]');
        
        const eyeNewPassword2 = document.getElementById('eye_new_password2');
        const newPassword2 = document.querySelector('input[name="new_password2"]');
        
        const togglePassword = (eye, password) => {
            if (password.type === 'password') {
                password.type = 'text';
                eye.classList.add('fa-eye-slash');
            } else {
                password.type = 'password';
                eye.classList.remove('fa-eye-slash');
            }
        };
    
        eyeOldPassword.addEventListener('click', () => {
            togglePassword(eyeOldPassword, oldPassword);
        });
    
        eyeNewPassword1.addEventListener('click', () => {
            togglePassword(eyeNewPassword1, newPassword1);
        });
    
        eyeNewPassword2.addEventListener('click', () => {
            togglePassword(eyeNewPassword2, newPassword2);
        });
    </script>
    
</body>
</html>